"""empty message

Revision ID: 631264c25b98
Revises: d06e59eff6f2
Create Date: 2019-01-19 09:42:38.666354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631264c25b98'
down_revision = 'd06e59eff6f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('postsid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('postsauthor', sa.String(length=20), nullable=False),
    sa.Column('poststitle', sa.String(length=50), nullable=False),
    sa.Column('postscontent', sa.String(length=1000), nullable=False),
    sa.Column('poststime', sa.String(length=20), nullable=True),
    sa.Column('postsstatus', sa.String(length=20), nullable=True),
    sa.Column('postsimage', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('postsid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
